const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const emailService = require('./emailService');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_KEY_1 || process.env.GEMINI_KEY || 'fake_key');

async function generateAIReportSummary(studentData, assignmentData, quizData) {
  try {
    const prompt = `
      You are an expert academic evaluator. Write a small 1-paragraph summary of the student's performance based on:
      Student Name: ${studentData.name}
      Assignments total marks avg: ${assignmentData.avg_marks} / 10
      Quizzes avg marks: ${quizData.avg_marks} / 10
      Give brief actionable feedback. Do NOT use markdown. Just plain text.
    `;
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
    const result = await model.generateContent(prompt);
    return result.response.text().trim();
  } catch (err) {
    console.error("AI Report Generation Error:", err);
    return "AI Summary is unavailable at the moment.";
  }
}

async function sendStudentReport(studentId, parentEmail, studentData, assignmentData, quizData) {
  // Generate AI Summary
  const summary = await generateAIReportSummary(studentData, assignmentData, quizData);

  // Generate PDF
  const doc = new PDFDocument({ margin: 50 });
  const reportPath = path.join(__dirname, '..', 'reports', `Report_${studentId}_${Date.now()}.pdf`);
  
  // Ensure dir exists
  if (!fs.existsSync(path.join(__dirname, '..', 'reports'))) {
    fs.mkdirSync(path.join(__dirname, '..', 'reports'));
  }

  const writeStream = fs.createWriteStream(reportPath);
  doc.pipe(writeStream);

  const logoPath = path.join(__dirname, '..', 'public', 'mit_acsc_logo.png');
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, (doc.page.width - 400) / 2, 40, { width: 400 });
    doc.moveDown(6); 
  } else {
    doc.fontSize(20).fillColor('#8b1832').text('MIT Arts, Commerce and Science College', { align: 'center' });
    doc.moveDown(3);
  }

  doc.fontSize(18).fillColor('#8b1832').font('Helvetica-Bold').text('Student Performance Report', { align: 'center' });
  doc.moveDown(2);

  const startX = 50;
  let currentY = doc.y;

  doc.rect(startX, currentY, 512, 80).fillOpacity(0.05).fillAndStroke('#8b1832', '#8b1832');
  doc.fillOpacity(1);
  doc.fillColor('#000000');
  
  doc.fontSize(12).font('Helvetica-Bold').text('Student Name:', startX + 20, currentY + 20);
  doc.font('Helvetica').text(studentData.name, startX + 120, currentY + 20);
  
  doc.font('Helvetica-Bold').text('Roll No:', startX + 280, currentY + 20);
  doc.font('Helvetica').text(studentData.roll_no || 'N/A', startX + 350, currentY + 20);

  doc.font('Helvetica-Bold').text('Class:', startX + 20, currentY + 50);
  doc.font('Helvetica').text(studentData.class_name || 'N/A', startX + 120, currentY + 50);
  
  doc.moveDown(3);
  currentY = doc.y;

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#8b1832').text('Academic Performance', startX, currentY);
  doc.moveDown(1);
  currentY = doc.y;

  doc.rect(startX, currentY, 512, 25).fill('#8b1832');
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(12);
  doc.text('Assessment Type', startX + 20, currentY + 7);
  doc.text('Average Score', startX + 300, currentY + 7);

  doc.rect(startX, currentY + 25, 512, 25).stroke('#e5e7eb');
  doc.fillColor('#374151').font('Helvetica').fontSize(12);
  doc.text('Assignments', startX + 20, currentY + 32);
  doc.text(`${Number(assignmentData.avg_marks || 0).toFixed(2)} / 10`, startX + 300, currentY + 32);

  doc.rect(startX, currentY + 50, 512, 25).stroke('#e5e7eb');
  doc.fillColor('#374151').font('Helvetica').fontSize(12);
  doc.text('Quizzes', startX + 20, currentY + 57);
  doc.text(`${Number(quizData.avg_marks || 0).toFixed(2)} / 10`, startX + 300, currentY + 57);

  doc.moveDown(5);
  currentY = doc.y;

  doc.fontSize(14).font('Helvetica-Bold').fillColor('#8b1832').text('AI Evaluator Feedback', startX, currentY);
  doc.moveDown(1);
  currentY = doc.y;
  
  doc.rect(startX, currentY, 512, 120).fillOpacity(0.05).fillAndStroke('#3b82f6', '#93c5fd');
  doc.fillOpacity(1);
  doc.fillColor('#1e3a8a').fontSize(12).font('Helvetica');
  doc.text(summary, startX + 20, currentY + 20, {
    width: 470,
    align: 'justify',
    lineGap: 4
  });

  doc.end();

  // Wait for the PDF to finish writing
  await new Promise((resolve, reject) => {
    writeStream.on('finish', resolve);
    writeStream.on('error', reject);
  });

  // Send Email
  await emailService.sendEmail(
    parentEmail,
    `Student Report: ${studentData.name}`,
    `<p>Dear Parent,</p><p>Please find attached the performance report for <b>${studentData.name}</b> generated by CodeGurukul AI.</p><p>Best Regards,<br/>CodeGurukul Team</p>`,
    [
      {
        filename: 'Student_Report.pdf',
        path: reportPath
      }
    ]
  );

  return { summary, reportPath };
}

module.exports = {
  sendStudentReport
};
